[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/.next/server/app/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Render-Mode = "ssr"